### ISSUE TITLE
Unable to access Facebook photos

### ISSUE THREAD

**Issue by cosmointeractive** [jveldboom/facebook-gallery#21]
I tried implementing this script but am unsuccessful. I get "invalid page id or name" after entering the following: 
```php
if(empty($_GET['fid'])){$_GET['fid'] = '218908081677';}
```
That is the correct page id. What am I missing?

**Comment by jveldboom** [comment]
That is the correct page id, but the script is expecting your Facebook page name "newtestamentbaptistmission".

Since you already know the page id, you should comment out line 18 and uncomment line19 in the [class.facebook.php file](https://github.com/jveldboom/facebook-gallery/blob/master/class.facebook-gallery.php#L18-L19).

**Comment by cosmointeractive** [comment]
Thanks, I refactored the code to fit my needs
